### ISSUE TITLE
executable not generated

### ISSUE THREAD

**Issue by soloman817** [MSRCCS/Prajna#155]
hi, I built Prajna from master branch with VisualStudio. I start client without options. and I created an app, but it cannot generate any output. I checked the log, it says the process start failed, and I located the source, and try to print the executable name:

```
    let StartChild(startInfo : ProcessStartInfo) =
        if (CommonJob <> IntPtr.Zero) then
            printfn "---> %A" startInfo.FileName
            let proc = Process.Start(startInfo)
            let res = AssignProcessToJobObject(CommonJob, proc.Handle)
            if (not res) then
```

And now it prints out the path:

```
C:\Users\solom\Documents\Projects\Prajna\src\Client\Client\bin\Releasex64>PrajnaClient.exe
---> "C:\Prajna\Job1082\PrajnaTest.CS\A17E5B37B00DA042\PrajnaClientExt_PrajnaTest.CS.exe.exe"
```

Then I look into that path, that file really doesn't exist!! only one config file and many referenced dll there. Any idea?

**Comment by soloman817** [comment]
Here is the log, it is just exception that the executable cannot be found:

```
============== New Log File ======================= 
160218_065232.128140,1,Info,PrajnaMachineId is 290efbd143477d11
160218_065232.183034,1,Info,Initialize network stack with initial buffers: 128 max buffers: 33554 buffer size: 128000 network threads: 2
160218_065232.223496,1,Info,Start PrajnaClient at port 1082 (1100-1150)...................... Mode x64, 1 MB
160218_065232.225632,1,Info,Minimum threads: 16, Minimum I/O completion threads: 4
160218_065232.226249,1,Info,Maximum threads: 32767, Maximum I/O completion threads: 1000
160218_065232.227165,1,Info,Available threads: 32767, Available I/O completion threads: 1000
160218_065232.228716,1,Info,Start Parameters [||]
160218_065232.236007,1,Info,All command parsed ==== true
160218_065232.267405,1,Info,Authentication parameters: pwd=empty keyfile= keyfilepwd=empty
160218_065338.822098,13,Warning,Prajna.Core.SingleJobActionContainer.EncounterExceptionAtContainer : JobID=bbc3e2f0-39ed-4443-b30c-b1376e61c48c(0ms),[Encounter Exception @ Container] ___ ParseCommandAtDaemon( Start, Job) ___: exception of System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Prajna.Tools.InterProcess.StartChild(ProcessStartInfo startInfo) in C:\Users\solom\Documents\Projects\Prajna\src\tools\tools\interops.fs:line 181
   at <StartupCode$Prajna>.$Task.setExecutionType@285(ExecutedTaskHolder x, Task ta, JobTaskKind executeTypeOf, Int64 executeTicks, Unit unitVar0) in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\task.fs:line 360
   at Prajna.Core.ExecutedTaskHolder.StartProgram(Task ta) in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\task.fs:line 419
   at Prajna.Core.TaskQueue.AddSeparateTask(Task ta, NetworkCommandQueue queue) in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\task.fs:line 3284
   at Prajna.Core.TaskQueue.ExecuteTask(Task ta, NetworkCommandQueue queue) in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\task.fs:line 3776
   at Prajna.Core.Task.ParseTaskCommandAtDaemon(SingleJobActionContainer jobAction, NetworkCommandQueuePeer queue, ControllerCommand cmd, StreamBase`1 ms, TaskQueue taskQueue) in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\task.fs:line 2626
   at <StartupCode$Prajna>.$Task.ParseCommandAtDaemon@3170-18.Invoke(SingleJobActionContainer jobAction) in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\task.fs:line 3182
160218_065338.829389,13,Info,JobID=bbc3e2f0-39ed-4443-b30c-b1376e61c48c(14ms),Name: ContainerJob, send to KINGKONG exception of System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Prajna.Tools.InterProcess.StartChild(ProcessStartInfo startInfo) in C:\Users\solom\Documents\Projects\Prajna\src\tools\tools\interops.fs:line 181
   at <StartupCode$Prajna>.$Task.setExecutionType@285(ExecutedTaskHolder x, Task ta, JobTaskKind executeTypeOf, Int64 executeTicks, Unit unitVar0) in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\task.fs:line 360
   at Prajna.Core.ExecutedTaskHolder.StartProgram(Task ta) in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\task.fs:line 419
   at Prajna.Core.TaskQueue.AddSeparateTask(Task ta, NetworkCommandQueue queue) in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\task.fs:line 3284
   at Prajna.Core.TaskQueue.ExecuteTask(Task ta, NetworkCommandQueue queue) in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\task.fs:line 3776
   at Prajna.Core.Task.ParseTaskCommandAtDaemon(SingleJobActionContainer jobAction, NetworkCommandQueuePeer queue, ControllerCommand cmd, StreamBase`1 ms, TaskQueue taskQueue) in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\task.fs:line 2626
   at <StartupCode$Prajna>.$Task.ParseCommandAtDaemon@3170-18.Invoke(SingleJobActionContainer jobAction) in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\task.fs:line 3182
160218_065338.831556,13,Info,JobID=bbc3e2f0-39ed-4443-b30c-b1376e61c48c(16ms),Exception 1 has been received with message The system cannot find the file specified
160218_065406.939170,21,Error,Prajna.Core.Task.ErrorInSeparateApp : (Close,Job) Failed to find Job Action object for Job 8e6efb49-a806-44d9-8f0b-b6c4521a42fd, error has happened before? 
```

**Comment by soloman817** [comment]
even I cannot run the examples in the solution. It works with local cluster, but if I add `-cluster realcluster.lst`, then it fails, and gives:

```
Exception at DSetStartServiceAction.StartService, exception: System.Exception: Job fails as some source is not available.

PeerQueue Status :
   at Prajna.Service.DSetStartServiceAction`1.StartService() in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\service.fs:line 248

Unhandled Exception: System.Exception: Job fails as some source is not available.

PeerQueue Status :
   at Prajna.Service.DSetStartServiceAction`1.StartService() in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\service.fs:line 254
   at Prajna.Service.Service.startServiceOnCluster(Cluster cl, String serviceName, WorkerRoleEntryPoint serviceClass) in C:\Users\solom\Documents\Projects\Prajna\src\CoreLib\service.fs:line 403
   at Prajna.Examples.Common.Utility.RunExamples$cont@146(String clusterArg, Boolean useProcArg, IExample[] examplesToExecute, Unit unitVar) in C:\Users\solom\Documents\Projects\Prajna\samples\examples\Common\Utility.fs:line 179
   at Prajna.Examples.CSharp.Program.Main(String[] args) in C:\Users\solom\Documents\Projects\Prajna\samples\examples\CSharpExamples\Driver.cs:line 10
```

**Comment by msrccsbuild** [comment]
Can you describe what is the setup that you run the cluster. In particular, Prajna requires that: 1) daemon node runs on each node of the target cluster, 2) daemon listening port and job port specified in the port range is opened. Do you properly configure the cluster on the above option?

Thanks,
Jin

**Comment by soloman817** [comment]
Hi Jin, I think this problem solved, it is because of there is no ClientExt in the client folder. It works if I use build script to build the project or reference ClientExt from Client project to force it copy that ext stuff.
